{% set version = "1.3.0" %}

package:
  name: ccr
  version: {{ version }}

source:
  url: https://github.com/ccr/ccr/releases/download/v{{ version | replace(".","_") }}/ccr-{{ version }}.tar.gz
  sha256: bb892e3319e5d748e29453f801286ec2f82bf4074f2f86de0e9b1ba5f08995c6

build:
  number: 8
  # No windows build available
  # https://github.com/ccr/ccr/issues/166
  # https://github.com/ccr/ccr/issues/167
  skip: true  # [win]
  run_exports:
    # 2021/12/29 hmaarrfk
    # No information on https://abi-laboratory.pro/
    - {{ pin_subpackage('ccr', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - make  # [unix]
  host:
    - libnetcdf
    - hdf5
    - bzip2
    - zstd
    # No lz4 support yet
    # https://github.com/ccr/ccr/issues/20
    # - lz4-c
    # not sure if this exists on conda forge yet
    # - bitgroom

test:
  commands:
    - ccr-config --help
    - test -f ${PREFIX}/include/ccr.h            # [unix]
    - test -f ${PREFIX}/lib/libccr${SHLIB_EXT}   # [unix]
    - test ! -f ${PREFIX}/lib/libccr.a           # [unix]
    - cat ${PREFIX}/lib/libccr.settings          # [unix]
    # - ccr-config --has-bitgroom | grep yes       # [unix]
    - ccr-config --has-bzip2    | grep yes       # [unix]
    # - ccr-config --has-fortran  | grep yes       # [unix]
    # - ccr-config --has-lz4      | grep yes       # [unix]
    - ccr-config --has-zstd     | grep yes       # [unix]

about:
  home: https://github.com/ccr/ccr
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Community Codec Repository'
  description: |
    This project supports compression (and other) filters for netCDF/HDF5 files
    which are not natively supported by the netCDF C library.

  doc_url: https://ccr.github.io/ccr/
  dev_url: https://github.com/ccr/ccr

extra:
  recipe-maintainers:
    - hmaarrfk
